<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Payplug\Payments\Block\Info;

/**
 * @var Info $block
 * @var Escaper $escaper
 */
$specificInfo = $block->getSpecificInformation();
$title = $escaper->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <dt class="title"><?= $escaper->escapeHtml($title); ?></dt>
    <?php if ($specificInfo): ?>
        <dd class="content">
            <table class="data table">
                <caption class="table-caption"><?= $escaper->escapeHtml($title); ?></caption>
                <?php foreach ($specificInfo as $label => $value): ?>
                    <tr>
                        <th scope="row"><?= $escaper->escapeHtml($label) ?></th>
                        <td>
                            <?php
                            $formattedValue = implode("\n", $block->getValueAsArray($value, true));
                            ?>
                            <?= $escaper->escapeHtml(nl2br($escaper->escapeHtml($formattedValue))); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </dd>
    <?php endif;?>
</dl>
<?= $block->getChildHtml() ?>
