<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Payplug\Payments\ViewModel\UrlProvider;

/**
 * @var Escaper $escaper
 * @var Template $block
 * @var SecureHtmlRenderer $secureRenderer
 */

/** @var UrlProvider $urlProvider */
$urlProvider = $block->getData('urlProviderViewModel');
?>
<?php if ($urlProvider->isApplePayEnabled()) : ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', ['src' => $escaper->escapeUrl($urlProvider->getApplePaySdkUrl())], '', false); ?>
<?php endif; ?>
<?php $scriptContent = <<<JS
window.PAYPLUG_DOMAIN = '{$escaper->escapeUrl($urlProvider->getPayplugSecureUrl())}';
require.config({
    paths: {
        payplugIntegrated: '{$escaper->escapeUrl($urlProvider->getPayplugIntegratedPaymentJsUrl())}'
    }
});
JS;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptContent, false); ?>
