<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Payplug\Payments\Block\Formjs;

/**
 * @var Escaper $escaper
 * @var Formjs $block
 * @var SecureHtmlRenderer $secureRenderer
 */
?>
<?php foreach ($block->getJsUrls() as $url): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', ['src' => $escaper->escapeUrl($url)], '', false); ?>
<?php endforeach; ?>
<?php $scriptContent = 'window.PAYPLUG_DOMAIN = \'' . $escaper->escapeUrl($block->getPayplugSecureUrl()) . '\';' ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptContent, false); ?>
