<?php

declare(strict_types=1);

use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 */
?>

<div data-bind="scope: 'apple-pay-button'">
    <apple-pay-button
        buttonstyle="black"
        type="pay"
        class="hidden"
        data-bind="
            click: handleClick,
            css: {
                hidden: !isVisible() 
            }
    ">
    </apple-pay-button>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app" : {
                "components" : {
                    "apple-pay-button" : {
                        "component" : "Payplug_Payments/js/view/cart/apple-pay"
                    }
                }
            }
        }
    }
</script>
