<?php /** @var \Payplug\Payments\Block\Customer\CardList $block */?>
<?php $payplugCards = $block->getPayplugCards(); ?>
<?php if (!empty($payplugCards)) : ?>
    <table class="data-table saved-cards" id="my-saved-cards-table">
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
        <tr>
            <th class="customer_card_id"><?= __('Card #') ?></th>
            <th class="brand"><?= __('Brand') ?></th>
            <th class="last4"><?= __('Card Mask') ?></th>
            <th class="exp_date"><?= __('Expiration Date') ?></th>
            <th class="delete"><span class="nobr"><?= __('Delete') ?></span></th>
        </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($payplugCards as $payplugCard) : ?>
            <tr>
                <td class="customer_card_id"><?= $payplugCard->getCustomerCardId() ?></td>
                <td class="brand"><?= $payplugCard->getBrand() ?></td>
                <td class="last4"><?= $payplugCard->getLastFour() ?></td>
                <td class="exp_date">
                    <span class="nobr"><?= $block->getFormattedExpDate($payplugCard->getExpDate()) ?></span>
                </td>
                <td class="delete">
                    <a href="<?= $block->getDeleteCardUrl($payplugCard->getCustomerCardId()) ?>">
                        <?= __('Delete this card') ?>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else : ?>
    <p><?= __('You have no saved cards.'); ?></p>
<?php endif ?>
