<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Payplug\Payments\Block\Customer\CardList;

/**
 * @var Escaper $escaper
 * @var CardList $block
 */
?>
<?php $payplugCards = $block->getPayplugCards(); ?>
<?php if (!empty($payplugCards)): ?>
    <table class="data-table saved-cards" id="my-saved-cards-table">
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
        <tr>
            <th class="customer_card_id"><?= $escaper->escapeHtml(__('Card #')) ?></th>
            <th class="brand"><?= $escaper->escapeHtml(__('Brand')) ?></th>
            <th class="last4"><?= $escaper->escapeHtml(__('Card mask')) ?></th>
            <th class="exp_date"><?= $escaper->escapeHtml(__('Expiration Date')) ?></th>
            <th class="delete"><span class="nobr"><?= $escaper->escapeHtml(__('Delete')) ?></span></th>
        </tr>
        </thead>
        <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($payplugCards as $payplugCard): ?>
            <?php $customerCardId = $payplugCard->getCustomerCardId(); ?>
            <tr>
                <td class="customer_card_id"><?= $escaper->escapeHtml($customerCardId) ?></td>
                <td class="brand"><?= $escaper->escapeHtml($payplugCard->getBrand()) ?></td>
                <td class="last4"><?= $escaper->escapeHtml($payplugCard->getLastFour()) ?></td>
                <td class="exp_date">
                    <span class="nobr">
                        <?= $escaper->escapeHtml($block->getFormattedExpDate($payplugCard->getExpDate())) ?>
                    </span>
                </td>
                <td class="delete">
                    <a href="<?= $escaper->escapeUrl($block->getDeleteCardUrl($customerCardId)) ?>">
                        <?= $escaper->escapeHtml(__('Delete this card')) ?>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p><?= $escaper->escapeHtml(__('You have no saved cards.')); ?></p>
<?php endif ?>
