<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Payplug\Payments\Block\Form\Ondemand;

/**
 * @var Escaper $escaper
 * @var Ondemand $block
 */

$code = $escaper->escapeHtml($block->getMethodCode());
$sentBy = $block->getAdditionalData('sent_by');
$language = $block->getAdditionalData('language');
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>"
          style="display:none">
    <div class="field-type admin__field _required payment-link-sent-by">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_sent_by">
            <span><?= $escaper->escapeHtml(__('Sent by method')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_sent_by" name="payment[sent_by]"
                    class="required-entry admin__control-select">
                <?php foreach ($block->getSentByOptions() as $typeCode => $typeName): ?>
                    <option value="<?= $escaper->escapeHtml($typeCode) ?>"
                            <?php if ($typeCode == $sentBy): ?>selected="selected"<?php endif ?>
                    >
                        <?= $escaper->escapeHtml($typeName) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="field-number admin__field _required payment-link-sent-by-value">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_sent_by_value">
            <span><?= $escaper->escapeHtml(__('Mobile')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?= /* @noEscape */ $code ?>_sent_by_value" name="payment[sent_by_value]"
                   title="<?= $escaper->escapeHtml(__('Mobile / Email')) ?>" class="admin__control-text required-entry"
                   value="<?= /* @noEscape */ $block->getAdditionalData('sent_by_value') ?>"/>
        </div>
    </div>
    <div class="field-type admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_language">
            <span><?= $escaper->escapeHtml(__('Language')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_language"
                    name="payment[language]"
                    class="required-entry admin__control-select"
            >
                <?php foreach ($block->getLanguages() as $languageCode => $languageName): ?>
                    <option value="<?= $escaper->escapeHtml($languageCode) ?>"
                            <?php if ($languageCode == $language): ?>selected="selected"<?php endif ?>
                    >
                        <?= $escaper->escapeHtml($languageName) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="field-number admin__field">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_description">
            <span><?= $escaper->escapeHtml(__('Description')) ?></span>
        </label>
        <div class="admin__field-control">
            <textarea id="<?= /* @noEscape */ $code ?>_description"
                      name="payment[description]"
                      title="<?= $escaper->escapeHtml(__('Description')) ?>"
                      class="admin__control-text"
                      maxlength="<?= \Payplug\Payments\Helper\Ondemand::DESCRIPTION_MAX_LENGTH ?>"
            ><?= /* @noEscape */ $block->getAdditionalData('description') ?></textarea>
        </div>
    </div>
    <div class="field-number admin__field">
        <div class="admin__field-control">
            <?php $buttonTitle = __('Save'); ?>
            <button title="<?= $escaper->escapeHtml($buttonTitle); ?>"
                    type="button"
                    class="action-default scalable action-secondary"
            >
                <span><?= $escaper->escapeHtml($buttonTitle); ?></span>
            </button>
        </div>
    </div>
</fieldset>
