<?php
/**
 * Payplug - https://www.payplug.com/
 * Copyright © Payplug. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/**
 * @var View $block
 */
$price = $block->getProduct()->getFinalPrice(1);
?>
<div class="oney-wrapper oney-product">
    <?= $block->getChildBlock('payplug-payments-product-oney-simulation')
            ->setAmount($price)
            ->toHtml();
    ?>
</div>
