<?php
/**
 * Payplug - https://www.payplug.com/
 * Copyright © Payplug. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Payplug\Payments\Block\Oney\Simulation;
use Payplug\Payments\Gateway\Config\OneyWithoutFees;
use Payplug\Payments\ViewModel\Oney as OneyViewHelper;

/**
 * @var Escaper $escaper
 * @var Simulation $block
 * @var OneyViewHelper $oneyViewHelper
 */

$oneyViewHelper = $block->getData('oneyViewHelper');

$hasError = false;
$oneySimulation = $block->getOneySimulation();
$message = $oneySimulation->getMessage();
if (!$oneySimulation->getSuccess() || !empty($message)) {
    $hasError = true;
}
$isOneyWithoutFees = $oneySimulation->getMethod() === OneyWithoutFees::METHOD_CODE;
?>
<?php if ($hasError): ?>
    <p class="oneyPopin_error"><?= /* @noEscape */ $message; ?></p>
<?php else: ?>
    <button type="button" class="oneyPopin_close">
        <?= $escaper->escapeHtml(__('Close')); ?>
    </button>
    <span class="oneyPopin_title">
        <?php if ($isOneyWithoutFees): ?>
            <?= /* @noEscape */ __(
                'Pay %1without fees%2 %3by card%4',
                '<span class="underline">',
                '</span>',
                '<strong>',
                '</strong>'
            ); ?>
        <?php else: ?>
            <?= /* @noEscape */ __('Pay %1by card%2', '<strong>', '</strong>'); ?>
        <?php endif; ?>
    </span>
    <ul class="oneyPopin_navigation">
        <li data-type="3x">
            <button type="button">
                <?= $escaper->escapeHtml(__('Payment in %1', '3x')); ?>
            </button>
        </li>
        <li data-type="4x">
            <button type="button">
                <?= $escaper->escapeHtml(__('Payment in %1', '4x')); ?>
            </button>
        </li>
    </ul>
    <?php foreach ($oneySimulation->getOptions() as $option): ?>
        <span class="oneyPopin_option" data-type="<?= /* @noEscape */ $option->getType(); ?>">
            <ul>
                <li>
                    <span><b><?= $escaper->escapeHtml(__('For an amount of:')); ?></b></span>
                    <span>
                        <b>
                            <?= /* @noEscape */ $oneyViewHelper->currency($oneySimulation->getAmount()); ?>
                        </b>
                    </span>
                </li>
                <li>
                    <span><?= $escaper->escapeHtml(__('Contribution:')); ?></span>
                    <span>
                        <b>
                            <?= /* @noEscape */ $oneyViewHelper->currency($option->getFirstDeposit()); ?>
                        </b>
                    </span>
                </li>
                <?php if (!$isOneyWithoutFees): ?>
                    <li>
                        <small>
                            (<?= $escaper->escapeHtml(__('Financing cost:')); ?>
                            <b><?= /* @noEscape */ $oneyViewHelper->currency($option->getCost()); ?></b>
                            <?= $escaper->escapeHtml(__('TAEG:')); ?>
                            <b><?= /* @noEscape */ $option->getRate(); ?>%</b>)
                        </small>
                    </li>
                <?php endif; ?>
                <?php foreach ($option->getSchedules() as $i => $schedule): ?>
                    <li>
                        <span><?= $escaper->escapeHtml(__(sprintf('Installment %d:', $i + 1))); ?></span>
                        <span>
                            <b>
                                <?= /* @noEscape */ $oneyViewHelper->currency($schedule->getAmount()); ?>
                            </b>
                        </span>
                    </li>
                <?php endforeach; ?>
                <?php if (!$isOneyWithoutFees): ?>
                    <li>
                        <span><b><?= $escaper->escapeHtml(__('Total cost:')); ?></b></span>
                        <span>
                            <b>
                                <?= /* @noEscape */ $oneyViewHelper->currency($option->getTotalAmount()); ?>
                            </b>
                        </span>
                    </li>
                <?php else: ?>
                    <li>
                        <small>
                            (<?= $escaper->escapeHtml(__('Financing cost:')); ?>
                            <b><?= /* @noEscape */ $oneyViewHelper->currency(0); ?></b>
                            <?= $escaper->escapeHtml(__('TAEG:')); ?> <b>0%</b>)
                        </small>
                    </li>
                <?php endif; ?>
            </ul>
        </span>
    <?php endforeach; ?>
    <?php
    $oneyAmounts = $block->getOneyAmounts();
    $minAmount = 100;
    $maxAmount = 3000;
    if (is_array($oneyAmounts)) {
        $minAmount = $oneyAmounts['min_amount'] / 100;
        $maxAmount = $oneyAmounts['max_amount'] / 100;
    }
    $minAmount = $oneyViewHelper->currency($minAmount);
    $maxAmount = $oneyViewHelper->currency($maxAmount);
    $legalOney = 'Financing offer with mandatory deposit reserved for private individual between %1 and %2. ' .
        'Providing Oney acceptation. You have 14 days to renounce this offer after the subscription. ' .
        'Oney Bank - SA capital of 51 286 585€ - 34 Avenue de Flandre 59170 Croix - ' .
        '546 380 197 RCS Lille Métropole - n° Orias 07 023 261 www.orias.fr ' .
        'Correspondance : CS 60 006 - 59895 Lille Cedex - ' .
        '<a href="http://www.oney.fr" target="_blank">www.oney.fr</a>';
    if ($isOneyWithoutFees) {
        $legalOney = 'Offre de financement sans assurance avec apport obligatoire, réservée aux particuliers ' .
            'et valable pour tout achat de %1 à %2. Sous réserve d\'acceptation par Oney Bank. ' .
            'Vous disposez d\'un délai de 14 jours pour renoncer à votre crédit. Oney Bank - ' .
            'SA au capital de 51 286 585€ - 34 Avenue de Flandre 59170 Croix - ' .
            '546 380 197 RCS Lille Métropole - n° Orias 07 023 261 www.orias.fr ' .
            'Correspondance : CS 60 006 - 59895 Lille Cedex - ' .
            '<a href="http://www.oney.fr" target="_blank">www.oney.fr</a>';
    }
    ?>
    <span class="oneyPopin_legal">
        <?= /* @noEscape */ __($legalOney, $minAmount, $maxAmount); ?>
        <?php if ($block->isMerchandItalian()): ?>
            <span class="legal-it">
                <?php if (!$isOneyWithoutFees): ?>
                <a href="<?= $escaper->escapeUrl($block->getMoreInfoUrl()); ?>" target="_blank" download>
                    <?= $escaper->escapeHtml(__('More info')); ?>
                </a>
                <?php else: ?>
                <a href="<?= $escaper->escapeUrl($block->getMoreInfoUrlWithoutFees()); ?>" target="_blank" download>
                    <?= $escaper->escapeHtml(__('More info')); ?>
                </a>
                <?php endif; ?>
            </span>
        <?php endif; ?>
    </span>
<?php endif; ?>
