<?php
/** @var \Payplug\Payments\Block\Oney\Simulation $block */
$oneySimulation = $block->getOneySimulation(true);
$isOneyWithoutFees = $oneySimulation->getMethod() === \Payplug\Payments\Gateway\Config\OneyWithoutFees::METHOD_CODE;
$isItalianStore = $block->isItalianStore();
$hasError = false;
if (!$oneySimulation->getSuccess()) {
    $hasError = true;
}
?>
<div class="oneyCta<?= $isOneyWithoutFees ? ' oney-without-fees' : ''; ?><?= $isItalianStore ? ' oney-it' : ''; ?>">
    <button type="button"
            class="oneyCta_button<?php if ($hasError): ?> oneyCta_button-disabled<?php endif; ?>">
        <span><?= $block->escapeHtml(__('Or pay in')); ?></span>
        <span class="oneyCta_logo oneyLogo oneyLogo-x3x4"></span>
        <span class="oneyCta_tooltip oneyLogo oneyLogo-tooltip"></span>
    </button>
    <span class="oneyPopin<?php if ($hasError): ?> oneyPopin-error<?php endif; ?>"></span>
</div>

<script type="text/x-magento-init">
    {
        ".oneyCta": {
            "oneyPopin": {}
        }
    }
</script>