<?php

use Magento\Checkout\Block\Onepage\Success;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Payplug\Payments\ViewModel\CheckoutSuccessViewModel;

/** @var Success $block * */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var CheckoutSuccessViewModel $checkoutSuccessViewModel */
$checkoutSuccessViewModel = $block->getData('checkoutSuccessViewModel');
$orderIncrementId = (string)$block->getData('order_id');

if ($checkoutSuccessViewModel->needToInvalidateCustomerCartSection($orderIncrementId) === false) {
    return;
}
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Payplug_Payments/js/checkout/success/invalidate-cart-section": {}
        }
    }
</script>
