<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Payplug\Payments\Block\Info;

/**
 * @var Info $block
 * @var Escaper $escaper
 */
$specificInfo = $block->getAdminSpecificInformation();
$title = $block->getMethod()->getTitle();
?>
<?= $escaper->escapeHtml(__($title)) ?>
<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value): ?>
            <tr>
                <th><?= $escaper->escapeHtml(__($label)); ?>:</th>
                <td>
                    <?php
                    $formattedValue = implode(PHP_EOL, $block->getValueAsArray($value, true));
                    ?>
                    <?= /* @noEscape */  nl2br($escaper->escapeHtml($formattedValue)); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
