<?php
/**
 * @var \Payplug\Payments\Block\Info $block
 */
$specificInfo = $block->getAdminSpecificInformation();
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value) : ?>
            <tr>
                <th><?= $block->escapeHtml(__($label)) ?>:</th>
                <td>
                    <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
