<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Payplug\Payments\Block\InstallmentPlanInfo;

/**
 * @var Escaper $escaper
 * @var InstallmentPlanInfo $block
 */
$specificInfo = $block->getAdminSpecificInformation();
?>
<?= $escaper->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($specificInfo): ?>
    <p><?= /* @noEscape */ $specificInfo['status']; ?></p>
    <p>
        <?= $escaper->escapeHtml(sprintf('%s : %s', (string)__('Installment plan id'), $specificInfo['installment_plan_id'])); ?>
    </p>

    <table class="data-table admin__table-primary">
        <tr>
            <th><?= $escaper->escapeHtml(__('Date')); ?></th>
            <th><?= $escaper->escapeHtml(__('Amount')); ?></th>
            <th><?= $escaper->escapeHtml(__('Status')); ?></th>
            <th></th>
        </tr>
        <?php foreach ($specificInfo['payments'] as $key => $paymentInfo): ?>
            <tr>
                <td><?= /* @noEscape */ $paymentInfo['date']; ?></td>
                <td><?= /* @noEscape */ $paymentInfo['amount']; ?></td>
                <td><?= /* @noEscape */ $paymentInfo['status']; ?></td>
                <td>
                    <?php if (!empty($paymentInfo['details'])): ?>
                        <button type="button"
                                data-toggle="collapse"
                                data-target="#payment-detail-<?= /* @noEscape */ $key; ?>"
                                role="button"
                                aria-expanded="false"
                                aria-controls="payment-detail-<?= /* @noEscape */ $key; ?>"
                        >
                            <?= $escaper->escapeHtml(__('Details')); ?>
                        </button>
                    <?php endif; ?>
                </td>
            </tr>
            <?php if (!empty($paymentInfo['details'])): ?>
                <tr class="collapse" id="payment-detail-<?= /* @noEscape */ $key; ?>" style="display: none;">
                    <td colspan="4">
                        <table class="data-table admin__table-secondary">
                            <?php foreach ($paymentInfo['details'] as $label => $value): ?>
                                <tr>
                                    <th><?= $escaper->escapeHtml(__($label)) ?>:</th>
                                    <td>
                                        <?php
                                        $formattedValue = implode(PHP_EOL, $block->getValueAsArray($value, true));
                                        ?>
                                        <?=  nl2br($escaper->escapeHtml($formattedValue)) ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>

    <?php if ($specificInfo['can_abort']): ?>
        <?php
        $orderId = $block->getInfo()->getOrder()->getId();
        $url = $block->getUrl('payplug_payments_admin/order/installmentPlanAbort', ['order_id' => $orderId]);
        ?>
        <a class="action-default"
           href="<?= $escaper->escapeHtmlAttr($url); ?>"
           onclick="return confirmAbortInstallmentPlan()"
        >
            <?= $escaper->escapeHtml(__('Abort')); ?>
        </a>
    <?php endif; ?>
<?php endif;?>

<?= $block->getChildHtml() ?>

<script>
    function confirmAbortInstallmentPlan() {
        return confirm('<?= $escaper->escapeJs(__('Are you sure you want to abort the installment plan?')); ?>');
    }
</script>
