<?php
/**
 * Payplug - https://www.payplug.com/
 * Copyright © Payplug. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Payplug\Payments\Block\OndemandInfo as Info;

/**
 * @var Info $block
 * @var Escaper $escaper
 */
$specificInfo = $block->getAdminSpecificInformation();
$title = $block->getMethod()->getTitle();
?>
<?= $escaper->escapeHtml(__($title)) ?>
<?php if ($specificInfo && isset($specificInfo['payments'])): ?>
<table class="data-table admin__table-primary">
    <tr>
        <th><?= $escaper->escapeHtml(__('Date')); ?></th>
        <th><?= $escaper->escapeHtml(__('Amount')); ?></th>
        <th><?= $escaper->escapeHtml(__('Status')); ?></th>
        <th></th>
    </tr>
    <?php foreach ($specificInfo['payments'] as $key => $paymentInfo): ?>
        <tr>
            <td><?= $escaper->escapeHtml($paymentInfo['date']) ?></td>
            <td><?= $escaper->escapeHtml($paymentInfo['amount']) ?></td>
            <td><?= $escaper->escapeHtml($paymentInfo['status']) ?></td>
            <td>
                <?php if (!empty($paymentInfo['details'])): ?>
                <button type="button"
                        class="toggle-details"
                        data-toggle="collapse"
                        data-target="#payment-detail-<?= $escaper->escapeHtmlAttr($key) ?>"
                        role="button"
                        aria-expanded="false"
                        aria-controls="payment-detail-<?= $escaper->escapeHtmlAttr($key) ?>">
                    <?= $escaper->escapeHtml(__('Details')); ?>
                </button>
                <?php endif; ?>
            </td>
        </tr>
        <?php if (!empty($paymentInfo['details'])): ?>
            <tr class="collapse"
                id="payment-detail-<?= $escaper->escapeHtmlAttr($key) ?>"
                style="display: none;">
                <td colspan="4">
                    <table class="data-table admin__table-secondary">
                        <?php foreach ($paymentInfo['details'] as $label => $value): ?>
                            <tr>
                                <th><?= $escaper->escapeHtml(__($label)) ?>:</th>
                                <td>
                                    <?php $formattedValue = implode(PHP_EOL, $block->getValueAsArray($value, true)); ?>
                                    <?= /* @noEscape */ nl2br($escaper->escapeHtml($formattedValue)) ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </td>
            </tr>

            <script>
                require([
                    'jquery',
                ], function ($) {
                    $('.toggle-details').on('click', function() {
                        const targetId = $(this).data('target');
                        const targetElement = $(targetId);
                        if (targetElement.css('display') === 'none' || targetElement.css('display') === '') {
                            targetElement.css('display', 'table-row');
                        } else {
                            targetElement.css('display', 'none');
                        }
                    });
                });
            </script>
        <?php endif; ?>
    <?php endforeach; ?>
</table>
<?php endif; ?>

<?= $block->getChildHtml() ?>
