name: Issue Auto Response

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add automatic response
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "\Hello,\n \n Thank you for taking the time to open this issue.\n \n Please note that this Jira project is used by our development team for tracking scheduled work and is not monitored as an official support channel.\n \n To ensure your request is tracked correctly and receives a timely response, we kindly ask you to submit your issue through our official Help Center:\n https://support.payplug.com/hc/en-gb\n \n Our support team will be able to properly diagnose the situation and assist you there. This Jira issue will now be closed, as we centralize all support requests through our official channels.\n \n Thank you for your understanding.\n \n Best regards,\n The Payplug Team"
            })
      - name: Notify Slack
        env:
          SLACK_PLUGINS_WEBHOOK_URL: ${{ secrets.SLACK_PLUGINS_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"New GitHub Issue opened in *${{ github.repository }}*:\n${{ github.event.issue.title }}\n${{ github.event.issue.html_url }}\"
          }" $SLACK_PLUGINS_WEBHOOK_URL