# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: "pull_request"
env:
  PHPCS_SEVERITY: 10

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-coding-standard@master
