<?php

declare(strict_types=1);

use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 */
?>

<div data-bind="scope: 'cart-button'">
    <apple-pay-button
        buttonstyle="black"
        type="pay"
        class="hidden"
        data-bind="
            click: handleClick,
            css: { hidden: !isVisible() } ">
    </apple-pay-button>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app" : {
                "components" : {
                    "cart-button" : {
                        "component" : "Payplug_Payments/js/view/apple-pay/cart-button"
                    }
                }
            }
        }
    }
</script>
