<?php

declare(strict_types=1);

use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 */
?>

<div data-bind="scope: 'cartButton'">
    <apple-pay-button
        buttonstyle="black"
        type="pay"
        class="hidden"
        data-bind="
            click: handleClick,
            css: { hidden: !isVisible() } ">
    </apple-pay-button>

    <!-- ko foreach: getRegion('messages') -->
    <!-- ko template: getTemplate() --><!-- /ko -->
    <!--/ko-->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app" : {
                "components" : {
                    "cartButton" : {
                        "component" : "Payplug_Payments/js/view/apple-pay/cart-button",
                        "workflowType": "shopping-cart",
                        "children": {
                            "messages": {
                                "component": "Magento_Ui/js/view/messages",
                                "displayArea": "messages"
                            }
                        }
                    }
                }
            }
        }
    }
</script>
