<?php

declare(strict_types=1);

use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 */
?>

<div class="product-action-apple-pay" 
     data-bind="scope: 'productButton'">
    <apple-pay-button
        buttonstyle="black"
        type="pay"
        class="hidden"
        data-bind="
            click: handleClick,
            css: { hidden: !isVisible() } ">
    </apple-pay-button>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app" : {
                "components" : {
                    "productButton" : {
                        "component" : "Payplug_Payments/js/view/apple-pay/product-button",
                        "workflowType": "product"
                    }
                }
            }
        }
    }
</script>
